--- 

machines: 

  - ['Ansible.master', '172.16.0.10', '1024', '1', 'debian/buster64']
  - ['Docker1', '172.16.0.20', '1024', '1', 'debian/buster64']
  - ['Docker2', '172.16.0.30', '1024', '1', 'centos/7']
