Vagrant.configure("2") do |config|

  require 'yaml'
  if File.file?('config.yaml')
    conf = YAML.load_file('config.yaml')
  else
    raise "Configuration file 'config.yaml' does not exist"
  end

  if ARGV[1] and ARGV[1] != conf['vmname']
    conf['vmname'] = ARGV[1]
  end

  conf['machines'].each do |vmname, ip, memory, cpus, box|
    config.vm.define "#{vmname}" do |vm|
      vm.vm.box = "#{box}" || "debian/buster64"
      vm.vm.hostname = "#{vmname}"
      vm.vm.network "private_network", ip: "#{ip}"
      vm.vm.provider "virtualbox" do |v|
        v.memory = "#{memory}"
        v.cpus = "#{cpus}"
        v.name = "#{vmname}"
      end

      if vm.vm.hostname == 'Ansible.master'
        vm.vm.provision :shell do |shell|
            shell.path = "install_ansible.sh"
        end   
      end

    end
  end

end